// AUTO-GENERATED by scripts/parse-labels.mjs — do not edit manually
// Re-generate: node scripts/parse-labels.mjs scripts/labels.json

export interface Hotspot {
  id: string;
  label: string;
  href: string;
  x: number;      // left edge — % of image width
  y: number;      // top edge  — % of image height
  width: number;  // % of image width
  height: number; // % of image height
  phase: number;  // minimum phase required to show this destination
  timeLock?: boolean; // true = Cave 7-day time lock
}

/** Hotspots for the boy day mobile island image */
export const boyDayMobileHotspots: Hotspot[] = [
  {
    "id": "garden",
    "label": "Garden",
    "href": "/garden",
    "phase": 1,
    "x": 73,
    "y": 54.79,
    "width": 14.52,
    "height": 4.92
  },
  {
    "id": "school",
    "label": "School",
    "href": "/school",
    "phase": 3,
    "x": 29.69,
    "y": 49.68,
    "width": 12.29,
    "height": 2.99
  },
  {
    "id": "home",
    "label": "Home",
    "href": "/home",
    "phase": 2,
    "x": 6.86,
    "y": 39.69,
    "width": 12.89,
    "height": 2.58
  },
  {
    "id": "rest-house",
    "label": "Rest House",
    "href": "/rest-house",
    "phase": 3,
    "x": 83.52,
    "y": 45.76,
    "width": 11.23,
    "height": 2.9
  },
  {
    "id": "lighthouse",
    "label": "Lighthouse",
    "href": "/lighthouse",
    "phase": 1,
    "x": 86.05,
    "y": 11.64,
    "width": 13.44,
    "height": 3.97
  },
  {
    "id": "fair",
    "label": "Fair",
    "href": "/fair",
    "phase": 3,
    "x": 50.42,
    "y": 44.9,
    "width": 16.87,
    "height": 5.02
  },
  {
    "id": "treasure-box",
    "label": "Treasure Box",
    "href": "/treasure-box",
    "phase": 2,
    "x": 27.84,
    "y": 19.48,
    "width": 15.65,
    "height": 3.9
  },
  {
    "id": "club-house",
    "label": "Club House",
    "href": "/club-house",
    "phase": 3,
    "x": 28.45,
    "y": 29.12,
    "width": 17.34,
    "height": 3.95
  },
  {
    "id": "cave",
    "label": "Cave",
    "href": "/cave",
    "phase": 1,
    "timeLock": true,
    "x": 7.64,
    "y": 16.3,
    "width": 13.92,
    "height": 4.2
  }
];

/** Hotspots for the boy day desktop island image */
export const boyDayDesktopHotspots: Hotspot[] = [
  {
    "id": "cave",
    "label": "Cave",
    "href": "/cave",
    "phase": 1,
    "timeLock": true,
    "x": 19.36,
    "y": 23.87,
    "width": 6.17,
    "height": 5.62
  },
  {
    "id": "treasure-box",
    "label": "Treasure Box",
    "href": "/treasure-box",
    "phase": 2,
    "x": 32.41,
    "y": 28.98,
    "width": 7.02,
    "height": 5.75
  },
  {
    "id": "club-house",
    "label": "Club House",
    "href": "/club-house",
    "phase": 3,
    "x": 44.08,
    "y": 35.46,
    "width": 8.25,
    "height": 6.17
  },
  {
    "id": "fair",
    "label": "Fair",
    "href": "/fair",
    "phase": 3,
    "x": 54.99,
    "y": 53.14,
    "width": 6.94,
    "height": 6.44
  },
  {
    "id": "rest-house",
    "label": "Rest House",
    "href": "/rest-house",
    "phase": 3,
    "x": 79.98,
    "y": 51.79,
    "width": 8.2,
    "height": 4.37
  },
  {
    "id": "home",
    "label": "Home",
    "href": "/home",
    "phase": 2,
    "x": 32.11,
    "y": 45.26,
    "width": 4.47,
    "height": 3.97
  },
  {
    "id": "garden",
    "label": "Garden",
    "href": "/garden",
    "phase": 1,
    "x": 67.6,
    "y": 62.65,
    "width": 6.84,
    "height": 5.94
  },
  {
    "id": "lighthouse",
    "label": "Lighthouse",
    "href": "/lighthouse",
    "phase": 1,
    "x": 79.02,
    "y": 13.3,
    "width": 8.78,
    "height": 7.16
  },
  {
    "id": "school",
    "label": "School",
    "href": "/school",
    "phase": 3,
    "x": 41.92,
    "y": 57.79,
    "width": 6.62,
    "height": 5.12
  }
];

/** Hotspots for the boy night mobile island image */
export const boyNightMobileHotspots: Hotspot[] = [
  {
    "id": "garden",
    "label": "Garden",
    "href": "/garden",
    "phase": 1,
    "x": 73,
    "y": 60.49,
    "width": 14.52,
    "height": 4.92
  },
  {
    "id": "school",
    "label": "School",
    "href": "/school",
    "phase": 3,
    "x": 33.11,
    "y": 55.04,
    "width": 13.11,
    "height": 3.5
  },
  {
    "id": "home",
    "label": "Home",
    "href": "/home",
    "phase": 2,
    "x": 8.64,
    "y": 45.33,
    "width": 12.91,
    "height": 3.63
  },
  {
    "id": "rest-house",
    "label": "Rest House",
    "href": "/rest-house",
    "phase": 3,
    "x": 83.96,
    "y": 51.27,
    "width": 12.9,
    "height": 3.36
  },
  {
    "id": "lighthouse",
    "label": "Lighthouse",
    "href": "/lighthouse",
    "phase": 1,
    "x": 84.01,
    "y": 19,
    "width": 13.44,
    "height": 3.97
  },
  {
    "id": "fair",
    "label": "Fair",
    "href": "/fair",
    "phase": 3,
    "x": 54.05,
    "y": 51.4,
    "width": 16.87,
    "height": 5.02
  },
  {
    "id": "treasure-box",
    "label": "Treasure Box",
    "href": "/treasure-box",
    "phase": 2,
    "x": 25.82,
    "y": 27.51,
    "width": 15.65,
    "height": 3.9
  },
  {
    "id": "club-house",
    "label": "Club House",
    "href": "/club-house",
    "phase": 3,
    "x": 31.63,
    "y": 36.09,
    "width": 17.34,
    "height": 3.95
  },
  {
    "id": "cave",
    "label": "Cave",
    "href": "/cave",
    "phase": 1,
    "timeLock": true,
    "x": 6.24,
    "y": 23.44,
    "width": 13.92,
    "height": 4.2
  }
];

/** Hotspots for the boy night desktop island image */
export const boyNightDesktopHotspots: Hotspot[] = [
  {
    "id": "cave",
    "label": "Cave",
    "href": "/cave",
    "phase": 1,
    "timeLock": true,
    "x": 21.23,
    "y": 24.98,
    "width": 6.17,
    "height": 5.62
  },
  {
    "id": "treasure-box",
    "label": "Treasure Box",
    "href": "/treasure-box",
    "phase": 2,
    "x": 34.41,
    "y": 30.31,
    "width": 7.02,
    "height": 5.75
  },
  {
    "id": "club-house",
    "label": "Club House",
    "href": "/club-house",
    "phase": 3,
    "x": 44.7,
    "y": 37.45,
    "width": 8.25,
    "height": 6.17
  },
  {
    "id": "fair",
    "label": "Fair",
    "href": "/fair",
    "phase": 3,
    "x": 55.99,
    "y": 52.47,
    "width": 6.94,
    "height": 6.44
  },
  {
    "id": "rest-house",
    "label": "Rest House",
    "href": "/rest-house",
    "phase": 3,
    "x": 78.23,
    "y": 53.79,
    "width": 6.66,
    "height": 4.07
  },
  {
    "id": "home",
    "label": "Home",
    "href": "/home",
    "phase": 2,
    "x": 33.86,
    "y": 44.82,
    "width": 4.47,
    "height": 3.97
  },
  {
    "id": "garden",
    "label": "Garden",
    "href": "/garden",
    "phase": 1,
    "x": 67.6,
    "y": 62.65,
    "width": 6.84,
    "height": 5.94
  },
  {
    "id": "lighthouse",
    "label": "Lighthouse",
    "href": "/lighthouse",
    "phase": 1,
    "x": 79.74,
    "y": 17.39,
    "width": 7.77,
    "height": 5.63
  },
  {
    "id": "school",
    "label": "School",
    "href": "/school",
    "phase": 3,
    "x": 45.63,
    "y": 57.03,
    "width": 5.76,
    "height": 4.6
  }
];

/** Hotspots for the girl day mobile island image */
export const girlDayMobileHotspots: Hotspot[] = [
  {
    "id": "garden",
    "label": "Garden",
    "href": "/garden",
    "phase": 1,
    "x": 73.23,
    "y": 56.17,
    "width": 14.52,
    "height": 4.92
  },
  {
    "id": "school",
    "label": "School",
    "href": "/school",
    "phase": 3,
    "x": 32.44,
    "y": 49.53,
    "width": 12.29,
    "height": 2.99
  },
  {
    "id": "home",
    "label": "Home",
    "href": "/home",
    "phase": 2,
    "x": 6.4,
    "y": 38.93,
    "width": 12.89,
    "height": 2.58
  },
  {
    "id": "rest-house",
    "label": "Rest House",
    "href": "/rest-house",
    "phase": 3,
    "x": 83.52,
    "y": 45.76,
    "width": 11.23,
    "height": 2.9
  },
  {
    "id": "lighthouse",
    "label": "Lighthouse",
    "href": "/lighthouse",
    "phase": 1,
    "x": 84.46,
    "y": 13.34,
    "width": 13.44,
    "height": 3.97
  },
  {
    "id": "fair",
    "label": "Fair",
    "href": "/fair",
    "phase": 3,
    "x": 54.32,
    "y": 45.97,
    "width": 16.87,
    "height": 5.02
  },
  {
    "id": "treasure-box",
    "label": "Treasure Box",
    "href": "/treasure-box",
    "phase": 2,
    "x": 10.38,
    "y": 27.21,
    "width": 15.65,
    "height": 3.9
  },
  {
    "id": "club-house",
    "label": "Club House",
    "href": "/club-house",
    "phase": 3,
    "x": 30.29,
    "y": 27.75,
    "width": 17.34,
    "height": 3.95
  },
  {
    "id": "cave",
    "label": "Cave",
    "href": "/cave",
    "phase": 1,
    "timeLock": true,
    "x": 4.45,
    "y": 17.78,
    "width": 13.92,
    "height": 4.2
  }
];

/** Hotspots for the girl day desktop island image */
export const girlDayDesktopHotspots: Hotspot[] = [
  {
    "id": "cave",
    "label": "Cave",
    "href": "/cave",
    "phase": 1,
    "timeLock": true,
    "x": 20.42,
    "y": 23.86,
    "width": 6.17,
    "height": 5.62
  },
  {
    "id": "treasure-box",
    "label": "Treasure Box",
    "href": "/treasure-box",
    "phase": 2,
    "x": 33.42,
    "y": 29.83,
    "width": 7.02,
    "height": 5.75
  },
  {
    "id": "club-house",
    "label": "Club House",
    "href": "/club-house",
    "phase": 3,
    "x": 45.33,
    "y": 35.85,
    "width": 8.25,
    "height": 6.17
  },
  {
    "id": "fair",
    "label": "Fair",
    "href": "/fair",
    "phase": 3,
    "x": 58.42,
    "y": 52.95,
    "width": 6.94,
    "height": 6.44
  },
  {
    "id": "rest-house",
    "label": "Rest House",
    "href": "/rest-house",
    "phase": 3,
    "x": 78.5,
    "y": 52.35,
    "width": 6.66,
    "height": 4.07
  },
  {
    "id": "home",
    "label": "Home",
    "href": "/home",
    "phase": 2,
    "x": 33.32,
    "y": 44.66,
    "width": 4.47,
    "height": 3.97
  },
  {
    "id": "garden",
    "label": "Garden",
    "href": "/garden",
    "phase": 1,
    "x": 69.76,
    "y": 63.29,
    "width": 6.84,
    "height": 5.94
  },
  {
    "id": "lighthouse",
    "label": "Lighthouse",
    "href": "/lighthouse",
    "phase": 1,
    "x": 80.89,
    "y": 13.3,
    "width": 7.77,
    "height": 5.88
  },
  {
    "id": "school",
    "label": "School",
    "href": "/school",
    "phase": 3,
    "x": 45.53,
    "y": 57.04,
    "width": 7.05,
    "height": 4.86
  }
];

/** Hotspots for the girl night mobile island image */
export const girlNightMobileHotspots: Hotspot[] = [
  {
    "id": "garden",
    "label": "Garden",
    "href": "/garden",
    "phase": 1,
    "x": 73.23,
    "y": 56.17,
    "width": 14.52,
    "height": 4.92
  },
  {
    "id": "school",
    "label": "School",
    "href": "/school",
    "phase": 3,
    "x": 32.86,
    "y": 49.67,
    "width": 12.29,
    "height": 2.99
  },
  {
    "id": "home",
    "label": "Home",
    "href": "/home",
    "phase": 2,
    "x": 7.45,
    "y": 39.62,
    "width": 12.89,
    "height": 2.58
  },
  {
    "id": "rest-house",
    "label": "Rest House",
    "href": "/rest-house",
    "phase": 3,
    "x": 83.52,
    "y": 46.6,
    "width": 11.23,
    "height": 2.9
  },
  {
    "id": "lighthouse",
    "label": "Lighthouse",
    "href": "/lighthouse",
    "phase": 1,
    "x": 85.08,
    "y": 12.22,
    "width": 13.44,
    "height": 3.97
  },
  {
    "id": "fair",
    "label": "Fair",
    "href": "/fair",
    "phase": 3,
    "x": 53.49,
    "y": 46.8,
    "width": 16.87,
    "height": 5.02
  },
  {
    "id": "treasure-box",
    "label": "Treasure Box",
    "href": "/treasure-box",
    "phase": 2,
    "x": 10.17,
    "y": 29.58,
    "width": 15.65,
    "height": 3.9
  },
  {
    "id": "club-house",
    "label": "Club House",
    "href": "/club-house",
    "phase": 3,
    "x": 30.71,
    "y": 29.42,
    "width": 17.34,
    "height": 3.95
  },
  {
    "id": "cave",
    "label": "Cave",
    "href": "/cave",
    "phase": 1,
    "timeLock": true,
    "x": 4.45,
    "y": 17.78,
    "width": 13.92,
    "height": 4.2
  }
];

/** Hotspots for the girl night desktop island image */
export const girlNightDesktopHotspots: Hotspot[] = [
  {
    "id": "cave",
    "label": "Cave",
    "href": "/cave",
    "phase": 1,
    "timeLock": true,
    "x": 20.27,
    "y": 25.12,
    "width": 6.17,
    "height": 5.62
  },
  {
    "id": "treasure-box",
    "label": "Treasure Box",
    "href": "/treasure-box",
    "phase": 2,
    "x": 34.57,
    "y": 31.02,
    "width": 7.02,
    "height": 5.75
  },
  {
    "id": "club-house",
    "label": "Club House",
    "href": "/club-house",
    "phase": 3,
    "x": 46.39,
    "y": 37.74,
    "width": 8.25,
    "height": 6.17
  },
  {
    "id": "fair",
    "label": "Fair",
    "href": "/fair",
    "phase": 3,
    "x": 58.47,
    "y": 54.61,
    "width": 6.94,
    "height": 6.44
  },
  {
    "id": "home",
    "label": "Home",
    "href": "/home",
    "phase": 2,
    "x": 33.86,
    "y": 46.95,
    "width": 4.47,
    "height": 3.97
  },
  {
    "id": "school",
    "label": "School",
    "href": "/school",
    "phase": 3,
    "x": 47.3,
    "y": 59.74,
    "width": 6.91,
    "height": 5.88
  },
  {
    "id": "lighthouse",
    "label": "Lighthouse",
    "href": "/lighthouse",
    "phase": 1,
    "x": 81.33,
    "y": 16.11,
    "width": 8.06,
    "height": 6.39
  },
  {
    "id": "rest-house",
    "label": "Rest House",
    "href": "/rest-house",
    "phase": 3,
    "x": 81.1,
    "y": 54.52,
    "width": 7.34,
    "height": 5.63
  },
  {
    "id": "garden",
    "label": "Garden",
    "href": "/garden",
    "phase": 1,
    "x": 69.09,
    "y": 65.98,
    "width": 7.34,
    "height": 6.39
  }
];

